"""add_hashed_password_to_users

Revision ID: ff3d20ca3d24
Revises: 
Create Date: 2026-02-25 16:00:04.528760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff3d20ca3d24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitems', sa.Column('bundle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orderitems', 'bundles', ['bundle_id'], ['id'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.drop_column('orderitems', 'bundle_id')
    # ### end Alembic commands ###
